SET NAMES UTF8;
DROP DATABASE IF EXISTS mfw;
CREATE DATABASE mfw CHARSET=UTF8;
USE mfw;
CREATE TABLE nav(
   lid INT PRIMARY KEY AUTO_INCREMENT,
   pic VARCHAR(128)
);
INSERT INTO nav VALUES(null,'1.jpg');
INSERT INTO nav VALUES(null,'2.jpg');
INSERT INTO nav VALUES(null,'3.jpg');
INSERT INTO nav VALUES(null,'4.jpg');
INSERT INTO nav VALUES(null,'5.jpg');

 CREATE TABLE mfw_user(
   uid INT PRIMARY KEY AUTO_INCREMENT,
   phone BIGINT,
   pwd VARCHAR(16)
 )